import type {
  Organization,
  CrisisAlert,
  LeaderboardEntry,
  AIInsight,
  ActivityFeedItem,
} from "@/types";

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: "org-1",
    userId: "u1",
    name: "GreenFuture Alliance",
    role: "ngo",
    mission: "Accelerating climate resilience through community-led reforestation and clean energy access.",
    categories: ["climate-change", "energy"],
    location: { country: "Kenya", city: "Nairobi", lat: -1.2921, lng: 36.8219 },
    projects: [
      {
        id: "p1",
        title: "Solar Villages Initiative",
        description: "Deploying micro-grids to 50 rural communities",
        category: "energy",
        status: "active",
        fundingRequired: 250000,
        impactScore: 92,
      },
    ],
    resourcesNeeded: ["Solar panels", "Technical volunteers", "Funding"],
    resourcesAvailable: ["Local networks", "Training programs"],
    sdgGoals: [7, 13, 15],
    impactMetrics: {
      livesImpacted: 45000,
      carbonReduced: 12000,
      volunteersActive: 340,
      projectsCompleted: 28,
      sustainabilityScore: 94,
    },
    verified: true,
    collaborationStatus: "open",
    createdAt: "2024-01-15",
    updatedAt: "2025-05-01",
  },
  {
    id: "org-2",
    userId: "u2",
    name: "HealthBridge Tech",
    role: "startup",
    mission: "AI-powered telehealth connecting underserved populations to specialists worldwide.",
    categories: ["healthcare", "mental-health"],
    location: { country: "India", city: "Mumbai", lat: 19.076, lng: 72.8777 },
    projects: [
      {
        id: "p2",
        title: "Rural Telehealth Network",
        description: "24/7 AI triage and specialist consultations",
        category: "healthcare",
        status: "active",
        fundingRequired: 180000,
        impactScore: 88,
      },
    ],
    resourcesNeeded: ["Medical devices", "Cloud infrastructure"],
    resourcesAvailable: ["AI platform", "Medical partnerships"],
    sdgGoals: [3, 9],
    impactMetrics: {
      livesImpacted: 120000,
      carbonReduced: 500,
      volunteersActive: 890,
      projectsCompleted: 15,
      sustainabilityScore: 87,
    },
    verified: true,
    collaborationStatus: "open",
    createdAt: "2024-03-20",
    updatedAt: "2025-05-10",
  },
  {
    id: "org-3",
    userId: "u3",
    name: "SafeHaven Foundation",
    role: "ngo",
    mission: "Creating safe spaces and emergency response networks for women in crisis zones.",
    categories: ["women-safety", "disaster-management"],
    location: { country: "Bangladesh", city: "Dhaka", lat: 23.8103, lng: 90.4125 },
    projects: [
      {
        id: "p3",
        title: "Emergency Shelter Network",
        description: "Rapid deployment shelters with 24/7 support",
        category: "women-safety",
        status: "active",
        fundingRequired: 320000,
        impactScore: 96,
      },
    ],
    resourcesNeeded: ["Shelter materials", "Counselors", "Transport"],
    resourcesAvailable: ["Crisis hotline", "Volunteer network"],
    sdgGoals: [5, 11, 16],
    impactMetrics: {
      livesImpacted: 78000,
      carbonReduced: 200,
      volunteersActive: 1200,
      projectsCompleted: 42,
      sustainabilityScore: 91,
    },
    verified: true,
    collaborationStatus: "emergency",
    createdAt: "2023-08-10",
    updatedAt: "2025-05-20",
  },
  {
    id: "org-4",
    userId: "u4",
    name: "AquaLife Global",
    role: "company",
    mission: "Deploying smart water purification systems to water-scarce regions using IoT monitoring.",
    categories: ["water-scarcity", "climate-change"],
    location: { country: "Peru", city: "Lima", lat: -12.0464, lng: -77.0428 },
    projects: [
      {
        id: "p4",
        title: "Smart Wells Program",
        description: "IoT-monitored purification for 200 communities",
        category: "water-scarcity",
        status: "active",
        fundingRequired: 400000,
        impactScore: 90,
      },
    ],
    resourcesNeeded: ["IoT sensors", "Local partners"],
    resourcesAvailable: ["Purification tech", "Engineering team"],
    sdgGoals: [6, 13],
    impactMetrics: {
      livesImpacted: 200000,
      carbonReduced: 8000,
      volunteersActive: 150,
      projectsCompleted: 35,
      sustainabilityScore: 89,
    },
    verified: true,
    collaborationStatus: "open",
    createdAt: "2023-11-05",
    updatedAt: "2025-05-15",
  },
  {
    id: "org-5",
    userId: "u5",
    name: "EduReach University",
    role: "university",
    mission: "Bridging educational gaps through open-source learning platforms and scholarship programs.",
    categories: ["education", "hunger"],
    location: { country: "Nigeria", city: "Lagos", lat: 6.5244, lng: 3.3792 },
    projects: [
      {
        id: "p5",
        title: "Digital Classroom Africa",
        description: "Offline-capable learning for 1M students",
        category: "education",
        status: "active",
        fundingRequired: 150000,
        impactScore: 85,
      },
    ],
    resourcesNeeded: ["Tablets", "Content creators"],
    resourcesAvailable: ["Curriculum", "Research labs"],
    sdgGoals: [4, 2],
    impactMetrics: {
      livesImpacted: 500000,
      carbonReduced: 1000,
      volunteersActive: 2500,
      projectsCompleted: 60,
      sustainabilityScore: 86,
    },
    verified: true,
    collaborationStatus: "open",
    createdAt: "2022-06-01",
    updatedAt: "2025-05-18",
  },
];

export const MOCK_CRISIS_ALERTS: CrisisAlert[] = [
  {
    id: "crisis-1",
    type: "flood",
    severity: "critical",
    region: "Sylhet Division",
    country: "Bangladesh",
    lat: 24.8949,
    lng: 91.8687,
    description: "Severe flooding affecting 2M people. Immediate shelter and medical aid required.",
    detectedAt: new Date().toISOString(),
    organizationsNotified: 47,
    actionPlan:
      "Deploy emergency shelters, connect HealthBridge Tech for telehealth, route AquaLife water systems.",
  },
  {
    id: "crisis-2",
    type: "wildfire",
    severity: "high",
    region: "Alberta",
    country: "Canada",
    lat: 53.9333,
    lng: -116.5765,
    description: "Wildfire spreading rapidly. Evacuation zones established.",
    detectedAt: new Date(Date.now() - 3600000).toISOString(),
    organizationsNotified: 23,
  },
  {
    id: "crisis-3",
    type: "health",
    severity: "medium",
    region: "São Paulo",
    country: "Brazil",
    lat: -23.5505,
    lng: -46.6333,
    description: "Dengue outbreak detected. Healthcare resources mobilizing.",
    detectedAt: new Date(Date.now() - 7200000).toISOString(),
    organizationsNotified: 31,
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    organizationId: "org-3",
    name: "SafeHaven Foundation",
    impactScore: 96,
    collaborationScore: 94,
    badges: ["Crisis Hero", "SDG Champion", "Verified"],
  },
  {
    rank: 2,
    organizationId: "org-1",
    name: "GreenFuture Alliance",
    impactScore: 94,
    collaborationScore: 91,
    badges: ["Climate Leader", "Verified"],
  },
  {
    rank: 3,
    organizationId: "org-4",
    name: "AquaLife Global",
    impactScore: 90,
    collaborationScore: 88,
    badges: ["Water Guardian", "Verified"],
  },
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: "insight-1",
    title: "Climate Hotspot Alert",
    summary:
      "East Africa showing 23% increase in drought risk. Recommend pairing GreenFuture Alliance with AquaLife Global for water-energy synergy.",
    category: "climate-change",
    confidence: 0.91,
    timestamp: new Date().toISOString(),
  },
  {
    id: "insight-2",
    title: "Healthcare Gap Detected",
    summary:
      "Rural India has 40% specialist shortage. HealthBridge Tech + EduReach University partnership could train 500 community health workers.",
    category: "healthcare",
    confidence: 0.87,
    timestamp: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "insight-3",
    title: "High-Impact Collaboration Opportunity",
    summary:
      "NGO A and Startup B share 94% mission compatibility in disaster response. Predicted collaboration success: 89%.",
    category: "global",
    confidence: 0.94,
    timestamp: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const MOCK_ACTIVITY_FEED: ActivityFeedItem[] = [
  {
    id: "a1",
    type: "collaboration",
    message: "GreenFuture Alliance partnered with AquaLife Global",
    organization: "GreenFuture Alliance",
    region: "East Africa",
    timestamp: new Date().toISOString(),
  },
  {
    id: "a2",
    type: "crisis",
    message: "Crisis Response activated in Bangladesh — 47 organizations alerted",
    region: "Bangladesh",
    timestamp: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: "a3",
    type: "volunteer",
    message: "234 volunteers matched to flood relief operations",
    region: "Sylhet",
    timestamp: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: "a4",
    type: "project",
    message: "Digital Classroom Africa reached 100,000 students milestone",
    organization: "EduReach University",
    timestamp: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "a5",
    type: "donation",
    message: "Verified transparent donation: $50,000 to SafeHaven Foundation",
    organization: "SafeHaven Foundation",
    timestamp: new Date(Date.now() - 1200000).toISOString(),
  },
];
